server:
    port: 8085
spring:
  cloud:
    open-feign:
      client:
        config:
          queue-client:
            url: "http://localhost:8080/"
  data:
    mongodb:
      initialization-mode: always
      uri: mongodb://localhost:27017/upa
  liquibase:
    change-log:
      classpath: db/db-json/master.json
    enabled: true